//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute("VinhKhanh.BackendApi-5a02726f-10e8-4cbf-ac59-1be088f5b89c")]
[assembly: System.Reflection.AssemblyCompanyAttribute("VinhKhanh.BackendApi")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+d0c90a0ecc039351023e7f34d2bed9f7f305a862")]
[assembly: System.Reflection.AssemblyProductAttribute("VinhKhanh.BackendApi")]
[assembly: System.Reflection.AssemblyTitleAttribute("VinhKhanh.BackendApi")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

